<a href="https://colab.research.google.com/github/AshiqueRehman/FaceMask-detection-FInal-year-Thesis-Project/blob/main/project_1_ad_sale_prediction_from_ext_customer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  Ad. Sale Prediction From Ext customer



**Importing Liabraries**

In [ ]:
import pandas as pd  # Useful for loading the dataset
import numpy as np  # to perform  array


**Choose Dataset file from Local Directory**

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving dataset.csv to dataset (3).csv


**Load Dataset**

In [ ]:
dataset = pd.read_csv("dataset.csv")
print(dataset)

     Age  Salary   Status
0     51    51408       0
1     34    83327       1
2     91    44525       1
3     93    98703       1
4     49    57908       1
..   ...      ...     ...
567   16    11788       0
568   79    50418       0
569   54    91780       0
570   24    84851       1
571   24    19991       1

[572 rows x 3 columns]


**Summarize Dataset**


In [ ]:
print(dataset.shape)#no. of rows and colums
print(dataset.head(5))# top values of data

(572, 3)
   Age  Salary   Status
0   51    51408       0
1   34    83327       1
2   91    44525       1
3   93    98703       1
4   49    57908       1


**Segression Dataset into X(input/independent variable) & Y(output/Dependent variable)**

In [ ]:
X= dataset.iloc[:,:-1].values
X

array([[   51, 51408],
       [   34, 83327],
       [   91, 44525],
       ...,
       [   54, 91780],
       [   24, 84851],
       [   24, 19991]])

In [ ]:
Y= dataset.iloc[:,-1].values
Y

array([0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1,


**Splitting Dataset into Train and Testt**

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test =train_test_split(X,Y, test_size=0.25,random_state=0)

**Feature Scaling**

**Fit_Transform-** fit method is calculating the mean and variance of each of the features present in our data 

**Transform-** transform method is tranforming all the features using the respective mean and variance 
we want our test data to be a completely new and a surpirse set for our model **

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
print(X_train)

[[ 1.40271770e+00  1.46480818e+00]
 [-1.71085646e+00 -5.88461254e-01]
 [-1.67701326e+00 -1.13826105e+00]
 [-1.00014931e+00 -1.21695755e+00]
 [-9.66306116e-01 -8.16571167e-02]
 [-1.67701326e+00 -1.49002534e+00]
 [ 9.62756130e-01 -6.43861441e-01]
 [ 9.62756130e-01  4.43379687e-02]
 [ 1.16676198e-01  4.32958536e-02]
 [ 8.95069736e-01 -1.21574735e+00]
 [ 2.52048987e-01  1.65675907e+00]
 [-1.87912578e-01 -2.32394033e-01]
 [ 3.19735382e-01 -1.04235025e-02]
 [-3.57128565e-01  1.13381895e+00]
 [-7.29403735e-01  5.33695082e-01]
 [ 1.33503130e+00 -3.04165513e-01]
 [ 9.96599328e-01  1.34497739e-01]
 [-6.95560538e-01  5.59210095e-01]
 [-1.57548367e+00  5.66269585e-01]
 [ 8.61226538e-01  8.52145307e-01]
 [ 1.16676198e-01 -1.55769559e+00]
 [-1.40626768e+00  7.96341720e-01]
 [-7.29403735e-01  7.07761931e-01]
 [ 8.61226538e-01 -1.27413942e+00]
 [ 1.84362592e-01  1.65376719e+00]
 [ 5.22794565e-01 -1.55487180e+00]
 [ 1.19965851e+00  1.31484444e+00]
 [ 8.95069736e-01 -7.59502608e-01]
 [-8.64776524e-01 -4

**Training**

In [ ]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()#loading the algorithm
model.fit(X_train,Y_train )#train

LogisticRegression()

predicting , weather new customer with Age & salary will buy or not 

In [ ]:
age = int(input ("Enter the new customer age :"))
sal =int(input ("Enter the new customer salary :"))
newCust = [[age,sal]]
result = model.predict(sc.transform(newCust))
print(result)
if result==1:
  print("customer will buy ")
else:
  print("customer wont buy")

Enter the new customer age :91
Enter the new customer salary :44525
[1]
customer will buy 


Prediction for All Test Data

In [ ]:
y_pred = model.predict(X_test)
#print(np.concatenate((Y_pred.reshape(len(Y_pred),1), y_test.reshape(len(y_test),1)),1))

**Evalauting model**


In [ ]:
from sklearn.metrics import accuracy_score
print("Accuracy of the model :{0}%".format(accuracy_score(y_test,y_pred)*100))

Accuracy of the model :51.74825174825175%
